name: List subtasks

on:
  push:
    branches:
      - '**'
    paths:
      - '*/subtasks.json'
  workflow_dispatch:

jobs:
  run:
    if: ${{ github.repository != 'TNFSH-Programming-Contest/tps-starter' }}
    uses: TNFSH-Programming-Contest/tps-actions/.github/workflows/list-subtasks.yml@main
